const POKEMON_TYPE = {
  GET_LIST: 'GET_LIST',
  SET_POKEMON_PAGE_LIST: 'SET_POKEMON_PAGE_LIST',
  SET_VAR_QUERY_GET_POKEMON_LIST: 'SET_VAR_QUERY_GET_POKEMON_LIST',
  SET_QUERY_PAGINATION_POKEMON_LIST: 'SET_QUERY_PAGINATION_POKEMON_LIST'
}

export default POKEMON_TYPE;